
package br.edu.ifce.ppd.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ChatService", targetNamespace = "http://service.chat.ppd.ifce.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChatService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.edu.ifce.ppd.ws.Chat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveChat", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.RetrieveChat")
    @ResponseWrapper(localName = "retrieveChatResponse", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.RetrieveChatResponse")
    public Chat retrieveChat(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

}
