
package br.edu.ifce.ppd.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.chat.ppd.ifce.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.edu.ifce.ppd.ws.UserWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllUsersNearBy", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.ListAllUsersNearBy")
    @ResponseWrapper(localName = "listAllUsersNearByResponse", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.ListAllUsersNearByResponse")
    public List<UserWrapper> listAllUsersNearBy(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifce.ppd.ws.UserWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllUsers", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.ListAllUsers")
    @ResponseWrapper(localName = "listAllUsersResponse", targetNamespace = "http://service.chat.ppd.ifce.edu.br/", className = "br.edu.ifce.ppd.ws.ListAllUsersResponse")
    public List<UserWrapper> listAllUsers();

}
